# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_course.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(276, 257)
        Dialog.setStyleSheet("background-color:#2E2E2E")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 130, 231, 111))
        self.label.setStyleSheet("color:#D8D8D8;\n"
"font: 12pt \"Gadugi\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 251, 41))
        self.lineEdit.setStyleSheet("color: #ff8000;\n"
"font: 12pt \"Gadugi\";\n"
"background-color:#585858;\n"
"text-transform:uppercase;\n"
"border:none; ")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 251, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 12pt \"Gadugi\";\n"
"    color:#cccc00;\n"
"    background-color:#424242;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#ffd9b3;\n"
"    background-color:#848484;\n"
"}\n"
"QPushButton:pressed{\n"
"    color:#ff9933;\n"
"    background-color:#848484;\n"
"}")
        # self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Exchange Rates"))
        self.label.setText(_translate("Dialog", "Rate: "))
        self.pushButton.setText(_translate("Dialog", "GET"))



