# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caclulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calcalator(object):
    def setupUi(self, Calcalator):
        Calcalator.setObjectName("Calcalator")
        Calcalator.resize(381, 450)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Calcalator.setPalette(palette)
        Calcalator.setStyleSheet("\n"
"")
        self.gridLayoutWidget = QtWidgets.QWidget(Calcalator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 98, 379, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.qwe = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.qwe.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.qwe.setContentsMargins(0, 0, 0, 0)
        self.qwe.setHorizontalSpacing(1)
        self.qwe.setVerticalSpacing(0)
        self.qwe.setObjectName("qwe")
        self.pushButton_two = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_two.sizePolicy().hasHeightForWidth())
        self.pushButton_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_two.setFont(font)
        self.pushButton_two.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_two.setObjectName("pushButton_two")
        self.qwe.addWidget(self.pushButton_two, 3, 1, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plus.sizePolicy().hasHeightForWidth())
        self.pushButton_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.qwe.addWidget(self.pushButton_plus, 1, 3, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1#dadbde )\n"
"}R")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.qwe.addWidget(self.pushButton_clear, 0, 0, 1, 1)
        self.pushButton_five = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_five.sizePolicy().hasHeightForWidth())
        self.pushButton_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_five.setFont(font)
        self.pushButton_five.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_five.setObjectName("pushButton_five")
        self.qwe.addWidget(self.pushButton_five, 2, 1, 1, 1)
        self.pushButton_equals = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_equals.sizePolicy().hasHeightForWidth())
        self.pushButton_equals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0  #ffd1b3, stop:1 #ff751a)\n"
"}R")
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.qwe.addWidget(self.pushButton_equals, 4, 2, 1, 1)
        self.pushButton_seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_seven.sizePolicy().hasHeightForWidth())
        self.pushButton_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_seven.setFont(font)
        self.pushButton_seven.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.qwe.addWidget(self.pushButton_seven, 1, 0, 1, 1)
        self.pushButton_nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nine.sizePolicy().hasHeightForWidth())
        self.pushButton_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_nine.setFont(font)
        self.pushButton_nine.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.qwe.addWidget(self.pushButton_nine, 1, 2, 1, 1)
        self.pushButton_percent = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_percent.sizePolicy().hasHeightForWidth())
        self.pushButton_percent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.qwe.addWidget(self.pushButton_percent, 0, 3, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dot.sizePolicy().hasHeightForWidth())
        self.pushButton_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.qwe.addWidget(self.pushButton_dot, 4, 0, 1, 1)
        self.pushButton_multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_multiply.sizePolicy().hasHeightForWidth())
        self.pushButton_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.qwe.addWidget(self.pushButton_multiply, 3, 3, 1, 1)
        self.pushButton_plus_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plus_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_plus_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus_minus.setFont(font)
        self.pushButton_plus_minus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.qwe.addWidget(self.pushButton_plus_minus, 0, 2, 1, 1)
        self.pushButton_three = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_three.sizePolicy().hasHeightForWidth())
        self.pushButton_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_three.setFont(font)
        self.pushButton_three.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_three.setObjectName("pushButton_three")
        self.qwe.addWidget(self.pushButton_three, 3, 2, 1, 1)
        self.pushButton_one = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_one.sizePolicy().hasHeightForWidth())
        self.pushButton_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_one.setFont(font)
        self.pushButton_one.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_one.setObjectName("pushButton_one")
        self.qwe.addWidget(self.pushButton_one, 3, 0, 1, 1)
        self.pushButton_divided = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_divided.sizePolicy().hasHeightForWidth())
        self.pushButton_divided.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_divided.setFont(font)
        self.pushButton_divided.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_divided.setObjectName("pushButton_divided")
        self.qwe.addWidget(self.pushButton_divided, 4, 3, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.qwe.addWidget(self.pushButton_minus, 2, 3, 1, 1)
        self.pushButton_six = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_six.sizePolicy().hasHeightForWidth())
        self.pushButton_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_six.setFont(font)
        self.pushButton_six.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_six.setObjectName("pushButton_six")
        self.qwe.addWidget(self.pushButton_six, 2, 2, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zero.sizePolicy().hasHeightForWidth())
        self.pushButton_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_zero.setFont(font)
        self.pushButton_zero.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.qwe.addWidget(self.pushButton_zero, 4, 1, 1, 1)
        self.pushButton_eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eight.sizePolicy().hasHeightForWidth())
        self.pushButton_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_eight.setFont(font)
        self.pushButton_eight.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.qwe.addWidget(self.pushButton_eight, 1, 1, 1, 1)
        self.pushButton_four = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_four.sizePolicy().hasHeightForWidth())
        self.pushButton_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_four.setFont(font)
        self.pushButton_four.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_four.setObjectName("pushButton_four")
        self.qwe.addWidget(self.pushButton_four, 2, 0, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_del.sizePolicy().hasHeightForWidth())
        self.pushButton_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid gray;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"stop:0 #f6f7fa, stop:1 #dadbde)\n"
"}R")
        self.pushButton_del.setObjectName("pushButton_del")
        self.qwe.addWidget(self.pushButton_del, 0, 1, 1, 1)
        self.label_output = QtWidgets.QLabel(Calcalator)
        self.label_output.setGeometry(QtCore.QRect(0, 0, 371, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_output.sizePolicy().hasHeightForWidth())
        self.label_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.label_output.setFont(font)
        self.label_output.setStyleSheet("QLabel\n"
"{\n"
" qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
" \n"
"\n"
"}\n"
" background-color: white; ")
        self.label_output.setObjectName("label_output")

        self.retranslateUi(Calcalator)
        QtCore.QMetaObject.connectSlotsByName(Calcalator)

    def retranslateUi(self, Calcalator):
        _translate = QtCore.QCoreApplication.translate
        Calcalator.setWindowTitle(_translate("Calcalator", "Calculator"))
        self.pushButton_two.setText(_translate("Calcalator", "2"))
        self.pushButton_plus.setText(_translate("Calcalator", "+"))
        self.pushButton_clear.setText(_translate("Calcalator", "AC"))
        self.pushButton_five.setText(_translate("Calcalator", "5"))
        self.pushButton_equals.setText(_translate("Calcalator", "="))
        self.pushButton_seven.setText(_translate("Calcalator", "7"))
        self.pushButton_nine.setText(_translate("Calcalator", "9"))
        self.pushButton_percent.setText(_translate("Calcalator", "%"))
        self.pushButton_dot.setText(_translate("Calcalator", "."))
        self.pushButton_multiply.setText(_translate("Calcalator", "X"))
        self.pushButton_plus_minus.setText(_translate("Calcalator", "+/-"))
        self.pushButton_three.setText(_translate("Calcalator", "3"))
        self.pushButton_one.setText(_translate("Calcalator", "1"))
        self.pushButton_divided.setText(_translate("Calcalator", "/"))
        self.pushButton_minus.setText(_translate("Calcalator", "−"))
        self.pushButton_six.setText(_translate("Calcalator", "6"))
        self.pushButton_zero.setText(_translate("Calcalator", "0"))
        self.pushButton_eight.setText(_translate("Calcalator", "8"))
        self.pushButton_four.setText(_translate("Calcalator", "4"))
        self.pushButton_del.setText(_translate("Calcalator", "Del"))
        self.label_output.setText(_translate("Calcalator", "0"))



